sudo: false

language: python

python:
        - "3.5"
install:
        - pip install -r requirements.txt

script:
        - python -m pytest --doctest-modules --cov=./ --cov-report=xml

after_success:
        - codecov
