sudo: false

language: python
python:
        - "2.7"
        - "3.5"
install:
        - pip install -r requirements.txt
script:
        - python -m pytest --doctest-modules
        - python3 -m pytest --doctest-modules --cov=./

after_success:
        - codecov
