coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%

    patch: false

  precision: 3

comment:
  layout: "diff, files, reach"
  behavior: new
  require_changes: false
